# Generated by Django 4.1.1 on 2022-09-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
